from . import student
from . import department
from . import subject
from . import fee_structure
from . import semester
from . import teacher
from . import student_semester_fee
from . import student_mark
from . import product_category
from . import sale_order_line
from . import product_make
from . import teacher_leave